### PR TITLE
Grammar and spelling issues

### PR DESCRIPTION
**Pull request by daneb**

### CODE REVIEW

**Comment by daneb** [comment]
Not sure if that final paragraph is what you intended to say.

**Comment by spywhere** [comment]
The last part, what I try to means is...

When you type while terminal is running and printing output, unexpected result might happen since Javatar save the whole console logs to a variable (to restore when user try to delete the last character, you could try running an example from getting started and remove the text when prompt for user name to see what I means here) which might contains some of user's entry in which result to console is invalid.

Is that make sense? or it even more confuse than it is :P

**Comment by daneb** [comment]
Hi @spywhere 
Ok I think I got you, take a look at the commit after I've read your comment

**Comment by spywhere** [comment]
Alright, thanks for the corrections. Hopefully I'll publish it around tomorrow.

**Pull request merged**
